logging:
  level:
    com.jrprojects.tutorial: TRACE

server.error.include-message: always

management.endpoints.web.exposure.include: '*'

urls:
  database: "https://midatabase.com"

db:
  owner: "Josimar Reyes Campos"
  corp: "JR Emperium"
  project: "Springboot tutorial"
